import "./globals.css";
import Footer from "@/components/footer";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import Navbar from "@/components/navbar/navbar";
import ModalProvider from "@/providers/modal-provider";
import ToastProvider from "@/providers/toast-provider";

import { useLocale } from "next-intl";
import { notFound } from "next/navigation";

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

const urbanist = Urbanist({ subsets: ["latin"] });

{
  /* <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"> */
}
export const metadata: Metadata = {
  title: "Sanity Store",
  description: "Generated by create next app",
  viewport:
    "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no",
};

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const locale = useLocale();
  console.log(locale, "locale");
  console.log(params.locale);

  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={urbanist.className}>
        <ModalProvider />
        <ToastProvider />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
